version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: asdf1234
      MYSQL_DATABASE: mono
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks: [app-network]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pasdf1234"]
      interval: 5s
      timeout: 3s
      retries: 30

  mono-backend:
    build: ./mono-backend
    container_name: mono-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: -Xms256m -Xmx512m
      APP_CORS_ALLOWED_ORIGINS: http://localhost,http://localhost:3000,http://localhost:5173
    ports:
      - "8080:8080"
    networks: [app-network]

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
