version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: asdf1234
      MYSQL_DATABASE: mono
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mariadb

  mono-backend:
    build: ./mono-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  mono-frontend:
    build: ./mono-frontend
    ports:
      - "80:3000"
    depends_on:
      - mono-backend

volumes:
  db_data: